# Calamares keyboard module. Defaults to the German (no dead keys) layout.
---
xOrgConfFileName: "00-keyboard.conf"
convertedKeymapPath: "/usr/share/X11/xkb/symbols/pc"
writeEtcDefaultKeyboard: true

default_keyboard_model: "pc105"
default_keyboard_layout: "de"
default_keyboard_variant: "nodeadkeys"
