---
units:
  - name: sddm.service
    action: enable
    mandatory: false
  - name: NetworkManager.service
    action: enable
    mandatory: true
  - name: apparmor.service
    action: enable
    mandatory: false
  - name: ufw.service
    action: enable
    mandatory: false
  - name: power-profiles-daemon.service
    action: enable
    mandatory: false
  - name: fwupd.service
    action: enable
    mandatory: false
