efiBootLoader: "grub"
kernel: "/vmlinuz"
img: "/initrd.img"
fallback: "/initrd.img.old"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
timeout: 5

installEFIFallback: true
efiBootMgr: "efibootmgr"

# TODO: Add signed shim/grub path once Secure Boot signing infrastructure exists.
