---
# Debian initramfs-tools must be able to read Calamares' generated keyfile
# when the user installs to an encrypted root filesystem.
crypttabOptions: luks,keyscript=/bin/cat

tmpOptions:
    default:
        tmpfs: false
        options: ""
    ssd:
        tmpfs: true
        options: "defaults,noatime,mode=1777"
