---
overwrite: false
prefer_grub_d: true
keep_distributor: false

kernel_params:
  - quiet

defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: "saved"
    GRUB_SAVEDEFAULT: true
    GRUB_DISABLE_RECOVERY: true

always_use_defaults: false
