services:
  - name: "NetworkManager"
    mandatory: true
  - name: "lightdm"
    mandatory: false
  - name: "apparmor"
    mandatory: false
  - name: "bluetooth"
    mandatory: false
  - name: "cups"
    mandatory: false
  - name: "cups-browsed"
    mandatory: false
  - name: "ipp-usb"
    mandatory: false
  - name: "fwupd-refresh.timer"
    mandatory: false
  - name: "power-profiles-daemon"
    mandatory: false

disable:
  - "ssh"
  - "sshd"
