services:
  - name: "NetworkManager"
    mandatory: true
  - name: "lightdm"
    mandatory: false
  - name: "apparmor"
    mandatory: false
  - name: "bluetooth"
    mandatory: false

disable:
  - "ssh"
  - "sshd"
