showSupportUrl: true
showKnownIssuesUrl: false
requirements:
  requiredStorage: 16
  requiredRam: 2
  internetCheckUrl: https://deb.debian.org/
  check:
    - storage
    - ram
    - power
    - internet
  required:
    - storage
    - ram
