[greeter]
theme-name=Aptura-Classic
icon-theme-name=Aptura-Classic
font-name=Sans 10
background=/usr/share/backgrounds/aptura/aptura-default.svg
default-user-image=/usr/share/pixmaps/aptura.svg
user-background=false
xft-antialias=false
indicators=~host;~spacer;~clock;~spacer;~language;~session;~a11y;~power
