# Aptura OS Calamares configuration (Ubuntu base).
---
modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules ]

instances:
- id: aptura
  module: contextualprocess
  config: contextualprocess.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - initramfscfg
  - initramfs
  - grubcfg
  - bootloader
  - packages
  - umount
- show:
  - finished

branding: aptura

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
